# Generated by Django 2.2.16 on 2022-02-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220202_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
