# Generated by Django 2.2.16 on 2022-02-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220203_1031'),
        ('reviews', '0005_comment_rating_review'),
    ]

    operations = [
    ]
