# Generated by Django 2.2.16 on 2022-02-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220204_1614'),
        ('reviews', '0006_merge_20220204_1336'),
    ]

    operations = [
    ]
