# Generated by Django 2.2.16 on 2022-02-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20220204_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
